SELECT *
FROM AEROLINEA a JOIN VUELOS v ON a.IDAEROLINEA = v.IDAEROLINEA JOIN AEROPUERTO a2 ON v.IDAEROPUERTOORIGEN = a2.IDAEROPUERTO 
JOIN AEROPUERTO a3 ON v.IDAEROPUERTODESTINO = a3.IDAEROPUERTO JOIN AVION a4 ON v.IDAVION = a4.IDAVION JOIN FECHA f 
ON v.IDFECHALLEGADA = f.IDFECHA JOIN FECHA f2 ON v.IDFECHASALIDA = f2.IDFECHA JOIN HORA h ON v.IDHORALLEGADAREAL = h.IDHORA 
JOIN HORA h2 ON v.IDHORASALIDAREAL = h2.IDHORA JOIN OPERADORA o ON v.IDOPERADORA = o.IDOPERADORA;
