SELECT *
FROM ( SELECT v.IDAEROLINEA AS idAerolinea, aero.ESTADO AS estadoDestino, aero2.ESTADO AS estadoOrigen, 
				AVG(v.TIEMPOREALVUELO) AS mediaTiempoRealVuelo, GROUPING_ID(aero.ESTADO, aero2.ESTADO) 
	   FROM VUELOS v JOIN AEROPUERTO aero ON aero.IDAEROPUERTO = v.IDAEROPUERTODESTINO JOIN AEROPUERTO aero2 
	   			ON aero2.IDAEROPUERTO = v.IDAEROPUERTOORIGEN 
	   GROUP BY GROUPING SETS ((v.IDAEROLINEA, aero.ESTADO), (v.IDAEROLINEA, aero2.ESTADO)) ) vuelos, Aerolinea aerolinea 
WHERE vuelos.IDAEROLINEA = aerolinea.IDAEROLINEA;
