SELECT *
FROM  ( SELECT v.IDOPERADORA, a.ESTADO, COUNT(*) AS numVuelos
        FROM VUELOS v JOIN AEROPUERTO a ON a.IDAEROPUERTO = v.IDAEROPUERTODESTINO 
        GROUP BY GROUPING SETS((v.IDOPERADORA, a.ESTADO), (v.IDOPERADORA), (a.ESTADO)) ) tienda
        LEFT OUTER JOIN OPERADORA o2 ON o2.IDOPERADORA = tienda.IDOPERADORA;
