SELECT origen.ESTADO, origen.NOMBREAEROPUERTO, AVG(origen.TIEMPOREALVUELO), RANK() OVER ( 
			PARTITION BY origen.ESTADO ORDER BY AVG(origen.TIEMPOREALVUELO) DESC) rankingTiempoVuelo
FROM (SELECT * FROM (VUELOS v  JOIN AEROPUERTO a ON a.IDAEROPUERTO = v.IDAEROPUERTOORIGEN)) origen
GROUP BY ROLLUP(origen.ESTADO, origen.NOMBREAEROPUERTO);
