SELECT *
FROM (	SELECT v.IDAEROPUERTOORIGEN, a.CIUDAD, AVG(V.TIEMPODERETRASOLLEGADA) AS RetrasoMedioAeroOrigenCiudadDestino
		FROM VUELOS v JOIN AEROPUERTO a ON v.IDAEROPUERTODESTINO = a.IDAEROPUERTO 
		GROUP BY v.IDAEROPUERTOORIGEN, a.CIUDAD
		UNION
		SELECT v2.IDAEROPUERTOORIGEN, NULL, AVG(v2.TIEMPODERETRASOLLEGADA) AS RetrasoAeroOrigenMedioTotal
		FROM VUELOS v2 
		GROUP BY v2.IDAEROPUERTOORIGEN 
		UNION
		SELECT NULL, a2.CIUDAD, AVG(v3.TIEMPODERETRASOLLEGADA) AS RetrasoAeroDestinoMedioTotal
		FROM VUELOS v3 JOIN AEROPUERTO a2 ON v3.IDAEROPUERTODESTINO = a2.IDAEROPUERTO 
		GROUP BY a2.CIUDAD ) t, AEROPUERTO a2
WHERE a2.IDAEROPUERTO = t.IDAEROPUERTOORIGEN;
