SELECT *
FROM (	SELECT vuelo.IDAEROPUERTOORIGEN, aeropuerto.CIUDAD AS ciudadDestino, AVG(vuelo.TIEMPODERETRASOLLEGADA) AS RetrasoMedioAeropuertoOrigenCiudadDestino
		FROM Vuelos vuelo JOIN AEROPUERTO aeropuerto ON vuelo.IDAEROPUERTODESTINO = aeropuerto.IDAEROPUERTO 
		GROUP BY ROLLUP(vuelo.IDAEROPUERTOORIGEN, aeropuerto.CIUDAD)
		HAVING GROUPING(vuelo.IDAEROPUERTOORIGEN) != 1 OR GROUPING(aeropuerto.CIUDAD) != 1 ) t, AEROPUERTO a2
WHERE a2.IDAEROPUERTO = t.IDAEROPUERTOORIGEN;
