SELECT *
FROM (	SELECT v.IDAEROPUERTOORIGEN, a.CIUDAD, AVG(V.TIEMPODERETRASOLLEGADA) AS RetrasoMedioAeroOrigenCiudadDestino
		FROM VUELOS v JOIN AEROPUERTO a ON v.IDAEROPUERTODESTINO = a.IDAEROPUERTO 
		GROUP BY v.IDAEROPUERTOORIGEN, a.CIUDAD 
		UNION
		SELECT v2.IDAEROPUERTOORIGEN, NULL,  AVG(v2.TIEMPODERETRASOLLEGADA) AS RetrasoAeroOrigenMedioTotal
		FROM VUELOS v2 
		GROUP BY v2.IDAEROPUERTOORIGEN ) t, AEROPUERTO a2
WHERE a2.IDAEROPUERTO = t.IDAEROPUERTOORIGEN;
