\begin{lstlisting}
SELECT *
FROM ( SELECT o.IDOPERADORA , a.ESTADO, COUNT(*) AS numVuelos
       FROM (VUELOS v JOIN AEROPUERTO a ON a.IDAEROPUERTO = v.IDAEROPUERTODESTINO) JOIN OPERADORA o ON o.IDOPERADORA = v.IDOPERADORA 
       GROUP BY CUBE(o.IDOPERADORA , a.ESTADO)
       HAVING GROUPING(o.IDOPERADORA) != 1 OR GROUPING(a.ESTADO) != 1 ) tienda
       LEFT OUTER JOIN OPERADORA o2 ON o2.IDOPERADORA = tienda.IDOPERADORA;
