SELECT tabla.ESTADO, tabla.CIUDAD, tabla.NOMBREAEROPUERTO, tabla.IDAEROPUERTOORIGEN, tabla.IDAEROLINEA, tabla.groupingId, tabla.cuenta, a3.CODIGOAEROLINEA, a3.NOMBREAEROLINEA 
FROM ( SELECT tienda.ESTADO, tienda.CIUDAD, a2.NOMBREAEROPUERTO, tienda.IDAEROPUERTOORIGEN, tienda.IDAEROLINEA, tienda.groupingId, tienda.cuenta
		FROM(   SELECT a.ESTADO, a.CIUDAD, v.IDAEROPUERTOORIGEN, v.IDAEROLINEA, GROUPING_ID(a.CIUDAD, v.IDAEROPUERTOORIGEN, v.IDAEROLINEA) AS groupingId, COUNT(*) AS cuenta
				FROM VUELOS v JOIN AEROPUERTO a ON a.IDAEROPUERTO = v.IDAEROPUERTOORIGEN 
				WHERE TIEMPODERETRASOSALIDA > 0
				GROUP BY a.ESTADO, ROLLUP(a.CIUDAD, v.IDAEROPUERTOORIGEN, v.IDAEROLINEA) ) tienda LEFT OUTER JOIN AEROPUERTO a2 ON a2.IDAEROPUERTO = tienda.IDAEROPUERTOORIGEN ) tabla
		LEFT OUTER JOIN AEROLINEA a3 ON a3.IDAEROLINEA = tabla.IDAEROLINEA
